version: '3.8'

services:
  unity-streamer:
    build:
      context: .
      dockerfile: Dockerfile
    image: unity-webrtc-streamer
    container_name: unity-webrtc-streamer
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute,display
      - DISPLAY=:99
    ports:
      - "8080:8080"
      - "10000-10100:10000-10100/udp"
    shm_size: '1gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - unity-network

networks:
  unity-network:
    driver: bridge